### ISSUE TITLE
php -S ip:port -t public causes swagger blank page

### ISSUE THREAD

**Issue by harishajdarevic** [DarkaOnLine/L5-Swagger#193]
- L5-Swagger Version: 5.5.8.3    Swagger integration to Laravel 5
- PHP Version: PHP 7.2.14-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan 13 2019 10:05:18) ( NTS )
- OS: Ubuntu 16.04

### Description:
I'm using dockerized Laravel. 

This is portion of docker-compose.yml file:

```
  myapp-web:
      container_name: "myapp-api"
      image: hitalos/laravel:latest
      ports:
          - 4800:80
      volumes:
          - ./:/var/www
      networks:
          - dadilje
      # If you don't want to use default 'artisan serve' command, edit and uncomment the line below.
      command: php -S 0.0.0.0:80 -t public public/index.php

```
### Steps To Reproduce:

When I have above configuration swagger works, but when I changed start command from:

php -S 0.0.0.0:80 -t public public/index.php 
to
php -S 0.0.0.0:80 -t public

It stops to work throwing error:
https://i.imgur.com/kkSgS0I.png

Any advice will be appreciated.
