### ISSUE TITLE
Cannot be used in GCP App Engine Flex environment

### ISSUE THREAD

**Issue by leeuwd** [DarkaOnLine/L5-Swagger#211]
- L5-Swagger Version: 5.8.0
- PHP Version: 7.2.19
- OS: N/A

### Description:

The API doc page gives a white screen when requested on a Google Cloud Platform App Engine Flex environment. This is due to `404` responses on the assets:

![image](https://user-images.githubusercontent.com/1755190/60081412-fd472280-9731-11e9-96cf-5262fe2fe092.png)

LL5-Swagger is serving these file contents directly from the disk (i.e. `vendor/swagger-api/swagger-ui/dist/*`, see https://github.com/DarkaOnLine/L5-Swagger/blob/master/src/helpers.php#L30). App Engine Flex cannot serve static files generated by Composer, see https://issuetracker.google.com/issues/122644831).

Specifying a custom handler (https://cloud.google.com/appengine/docs/standard/php7/config/appref) does not work for the `vendor` directory.

Suggestion: enhance `swagger_ui_dist_path()` to allow setting a custom value for `$path` via Laravel's default config mechanism, with `vendor/swagger-api/swagger-ui/dist/` as default value.

**Comment by leeuwd** [comment]
Adding this in `app.yaml` doesn't work:

```yml
env: flex

runtime_config:
    document_root: public

handlers:
    - url: /docs/asset
      static_dir: vendor/swagger-api/swagger-ui/dist
```
